# [Info]
site_name: HowJul的学习笔记 # 左上角标题
site_url: https://howjul.github.io/note
site_author: howjul
site_description: site of howjul

# [Navigtion]
nav:
  - 🏡 开始: 
    - Home: index.md
    - 🐾 更新: update.md
    - 🐽 关于: about.md
    - 🥴 中二: head.md
    - 😇 友链: https://howjul.com/blogroll/
    - 👹 209志怪录: Friend/pet.md
    - 👽 丽泽秘闻: Friend/lize.md
    - 🌕 1/365 night: Friend/night.md
  # - 🌸 课程总结:
  #   - 说明: ./课程总结/index.md
  #   - 大三春夏: ./课程总结/大三春夏.md
  #   - 大三秋冬: ./课程总结/大三秋冬.md
  #   - 大二暑假: ./课程总结/大二暑假.md
  #   - 大二春夏: ./课程总结/大二春夏.md
  #   - 大二秋冬: ./课程总结/大二秋冬.md
  #   - 大一暑假: ./课程总结/大一暑假.md
  #   - 大一春夏: ./课程总结/大一春夏.md
  #   - 大一秋冬: ./课程总结/大一秋冬.md
  - 🌾 本科三年: https://www.yuque.com/howjul/rt9ms6
  - 🌈 课程笔记: 
    - 说明: ./course.md
    - 编译原理: https://www.yuque.com/howjul/rt9ms6
    - 硬件安全基础: https://www.yuque.com/howjul/rt9ms6
    - 网络安全原理与实践: https://www.yuque.com/howjul/rt9ms6
    - 面向信息安全的信号处理:
      - 第一章 信号与系统: 面向信息安全的信号处理/lec1.md
      - 第二章 信号频域分析: 面向信息安全的信号处理/lec2.md
      - 第三章 采样与滤波: 面向信息安全的信号处理/lec3.md
      - 第四章 语音信号处理: 面向信息安全的信号处理/lec4.md
      - 第五章 数字图像处理与安全: 面向信息安全的信号处理/lec5.md
      - 第六章 信息安全中的毫米波感知: 面向信息安全的信号处理/lec6.md
      - 第七章 无线通信安全: 面向信息安全的信号处理/lec7.md
    - 技术沟通:
      - 1.文献检索: 技术沟通/1 文献检索.md
      - 2.文献阅读: 技术沟通/2 文献阅读.md
      - 3.文献综述: 技术沟通/3 文献综述.md
      - 4.技术文档的结构: 技术沟通/4 技术文档的结构.md
      - 5.技术文档的语言: 技术沟通/5 技术文档的语言.md
      - 6.演示方法: 技术沟通/6 演示方法.md
      - 7.演讲方法: 技术沟通/7 演讲方法.md
    - 计算机动画: 计算机动画/复习.md 
    - 高级数据结构与算法分析:
      - 期末复习: ADS/ads.md
      - 1.AVL Tree&Splay Tree: ADS/1. AVL Tree&Splay Tree 2.28.md
      - 2.Red-Black Trees&B+ Trees: ADS/2. Red-Black Trees&B+ Trees3.7.md
      - 3.Inverted File Index: ADS/3. Inverted File Index.md
      - 4.Leftist Heaps and Skew Heaps: ADS/4. Leftist Heaps and Skew Heaps.md
      - 5.Binomial Queue: ADS/5. Binomial Queue.md
      - 6.Backtracking: ADS/6. Backtracking.md
      - 7.Divide and Conquer: ADS/7. Divide and Conquer.md
      - 8.Dynamic Programming: ADS/8. Dynamic Programming.md
      - 9.Greedy Algorithms: ADS/9. Greedy Algorithms.md
      - 10.NP-Completeness: ADS/10. NP-Completeness.md
      - 11.Approximation: ADS/11. Approximation.md
      - 12.Local Search: ADS/12. Local Search.md
      - 13.Randomized Algorithms: ADS/13. Randomized Algorithms.md
      - 14.Parallel Algorithms: ADS/14. Parallel Algorithms.md
      - 15.External Sorting: ADS/15. External Sorting.md
      - 参考: ADS/inference.md
    - 计算机系统III:
      - 第3课: 系统三/第三课 3.6.md
      - 第4课: 系统三/第四课 3.9.md
      - 第5课: 系统三/第五课 3.13.md
      - 第6课: 系统三/第六课 3.16.md
      - 第7课: 系统三/第七课 3.20.md
      - 第8课: 系统三/第八课 3.23.md
      - 第9课: 系统三/第九课 3.27.md
      - 第10课: 系统三/第十课 3.30.md
      - 第15课: 系统三/第十五课 4.17.md
      - 第16课: 系统三/第16课 4.20.md
      - 第17课: 系统三/第17课 4.24.md
      - 第18课: 系统三/第18课 4.27.md
      - 第19课: 系统三/第19课 5.4.md
      - 第20课: 系统三/第20课 5.8.md
      - 第21课: 系统三/第21课 5.11.md
      - 第22课: 系统三/第22课 5.15.md
      - 第23课: 系统三/第23课 5.18.md
      - 第24课: 系统三/第24课 5.22.md
      - 第25课: 系统三/第25课 5.25.md
      - 第26课: 系统三/第26课 5.29.md
      - 第27课: 系统三/第27课 6.1.md
      - 第28课: 系统三/第28课 6.5.md
      - 第29课: 系统三/第29课 6.8.md
      - 操作系统导论笔记: 系统三/操作系统导论笔记.md
      - lab1: 系统三/lab1.md
      - lab2: 系统三/lab2.md
      - lab3: 系统三/lab3.md
      - lab4: 系统三/lab4.md
      - lab5: 系统三/lab5.md
      - 期末: https://howjul.com/2023/11/15/%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%B3%BB%E7%BB%9F%E6%9C%9F%E6%9C%AB%E8%80%83%E8%AF%95%E7%9B%B8%E5%85%B3/
    - 密码学: 密码学/explain.md
    - 软件安全: 
      - 0.Introduce: 软件安全/0. Introduce.md
      - 1.Overview: 软件安全/1. Overview.md
      - 2.Basic Principles: 软件安全/2. Basic Principles.md
      - 3.Buffer Overflow: 软件安全/3. Buffer Overflow.md
      - 4.Ret2libc & ROP: 软件安全/4. Ret2libc & ROP.md
      - 5.ROP & BROP: 软件安全/5. ROP & BROP.md
      - 6.Format String Attack: 软件安全/6. 格式化字符串漏洞.md
      - 7.Static Analysis: 软件安全/7. 静态分析.md
      - 8.Symbolic&Concolic Execution: 软件安全/8. Symbolic&Concolic Execution.md
      - 9.Taint Analysis: 软件安全/9. Taint Analysis.md
      - 10.fuzz: 软件安全/10. fuzz.md
      - 11.SFI&CFI: 软件安全/11. SFI & CFI.md
    - 数据安全与隐私保护: 
      - 1.Course Overview: 数据安全/1. Course Overview.md
      - 2.User Authentication: 数据安全/2. User Authentication.md
      - 3.Unix Discretionary Access Control: 数据安全/3.  Unix Discretionary Access Control.md
      - 4.MAC and Intergrity Protection: 数据安全/4. MAC and Intergrity Protection.md
      - 5.Role Based Access Control: 数据安全/5. Role Based Access Control.md
      - 6.Modern Crypto: 数据安全/6. Modern Crypto.md
      - 7.Stream Ciphers and CPA Security: 数据安全/7. Stream Ciphers and CPA Security.md
      - 8.PRF, CPA Security and CCA Security: 数据安全/8. PRF, CPA Security and CCA Security.md
      - 9. Message Authentication Code: 数据安全/9. Message Authentication Code.md
      - 10. Number Theory Basics: 数据安全/10. Number Theory Basics.md
      - 11. Key Management and The Need for Public Key Cryptography: 数据安全/11. Key Management and The Need for Public Key Cryptography.md
      - 13. RSA Encryption: 数据安全/13. RSA Encryption.md
      - 14. Digital Signature: 数据安全/14. Digital Signature.md
      - 15. Differential Privacy: 数据安全/15. Differential Privacy.md
      - 展示（零知识证明）: 数据安全/零知识证明.md
    - 机器人导论: 
      - 第三课 微控制器: 机器人导论/第三课 3.6 微控制器.md
      - 第四课 机器人传感器: 机器人导论/第四课 3.10 机器人传感器.md
      - 第五课 机器人驱动原理概述: 机器人导论/第五课 3.13 机器人驱动原理概述.md
      - 第六课 机器人驱动原理概述-2: 机器人导论/第六课 3.17 机器人驱动原理概述-2.md
      - 第七课 机器人设计与传动-1: 机器人导论/第七课 3.20 机器人设计与传动-1.md
      - 第八课 机器人设计与传动-2: 机器人导论/第八课 3.24 机器人设计与传动-2.md
      - 第九课 机器人运动学和坐标变换: 机器人导论/第九课 3.27 机器人运动学和坐标变换.md
      - 第十课 里程估计: 机器人导论/第十课 3.31 里程估计.md
      - 第十一课 机器人视觉: 机器人导论/第十一课 4.3 机器人视觉.md
      - 第十二课 规划导论: 机器人导论/第十二课 4.7 规划导论.md
      - 第十三课 集群: 机器人导论/第十三课 4.10 集群.md
    - 中国现当代小说赏析: 
      - 中国现当代小说简脉: 中国现当代小说赏析/中国现当代小说赏析.md
      - 沈从文小说赏析: 中国现当代小说赏析/沈从文小说赏析.md
      - 张爱玲小说赏析: 中国现当代小说赏析/张爱玲小说赏析.md
      - 谌容小说赏析: 中国现当代小说赏析/谌容小说赏析.md
      - 余华小说赏析: 中国现当代小说赏析/余华小说赏析.md
      - 刘震云小说赏析: 中国现当代小说赏析/刘震云小说赏析.md
      - 鬼子小说赏析: 中国现当代小说赏析/鬼子小说赏析.md
    - 计算机系统II: 
      - 1.OS Services & Structures: 系统二/1. OS Services & Structures (11.7、11.14).md
      - 2.OS Structures: 系统二/2. OS Structures (11.17).md
      - 3.Process: 系统二/3. Process(11.17、11.21、11.24).md
      - 4.Threads: 系统二/4. Threads(11.24、11.28、12.1).md
      - 5.Threads_b: 系统二/5. Threads_b(12.1).md
      - 6.CPU_Scheduling: 系统二/6. CPU_Scheduling(12.5、12.8、12.12).md
      - 7.Mars: 系统二/7. Mars(12.12).md
      - 8.Synchronization Tools: 系统二/8. Synchronization Tools (12.14).md
      - 期末: https://howjul.com/2023/11/15/%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%B3%BB%E7%BB%9F%E6%9C%9F%E6%9C%AB%E8%80%83%E8%AF%95%E7%9B%B8%E5%85%B3/
    - 数据结构基础:
      - 期末复习: FDS/fds.md
      - exam: 
        - 说明: FDS/试卷/试卷.md
        - 21-22期中卷: FDS/试卷/21-22 期中卷.md
        - 期中卷: FDS/试卷/期中卷.md
      # - hw:
      #   - hw1-7: FDS/fds_hw/fds_hw1-7.md
      #   - hw8: FDS/fds_hw/fds_hw8.md
      #   - hw9: FDS/fds_hw/fds_hw9.md
      #   - hw10: FDS/fds_hw/fds_hw10.md
      #   - hw11: FDS/fds_hw/fds_hw11.md
      #   - hw12: FDS/fds_hw/fds_hw12.md
      #   - hw13: FDS/fds_hw/fds_hw13.md
      #   - hw14: FDS/fds_hw/fds_hw14.md
      #   - hw15: FDS/fds_hw/fds_hw15.md
      - lec:
        - lec1-6: FDS/fds_lec/fds_lec1-6.md
        - lec7: FDS/fds_lec/fds_lec7.md 
        - lec8: FDS/fds_lec/fds_lec8.md 
        - lec9: FDS/fds_lec/fds_lec9.md 
        - lec10: FDS/fds_lec/fds_lec10.md 
        - lec11: FDS/fds_lec/fds_lec11.md 
        - lec12: FDS/fds_lec/fds_lec12.md 
        - lec13-14: FDS/fds_lec/fds_lec13&&lec_14.md 
    - 面向对象程序设计:
      - 期末复习: OOP/oop.md
      - lec:
        - exam: OOP/oop_lec/oop_exam.md 
        - lec11: OOP/oop_lec/oop_lec11.md 
        - lec12: OOP/oop_lec/oop_lec12.md 
        - lec13: OOP/oop_lec/oop_lec13.md 
        - lec14: OOP/oop_lec/oop_lec14.md 
        - lec15: OOP/oop_lec/oop_lec15.md 
      - selfstudy:
        - self1: OOP/oop_self/oop_self1.md 
        - self2: OOP/oop_self/oop_self2.md 
        - self3: OOP/oop_self/oop_self3.md 
        - self4: OOP/oop_self/oop_self4.md 
        - self5: OOP/oop_self/oop_self5.md 
        - self6: OOP/oop_self/oop_self6.md 
        - self7: OOP/oop_self/oop_self7.md 
        - self8: OOP/oop_self/oop_self8.md 
        - self9: OOP/oop_self/oop_self9.md 
        - self10: OOP/oop_self/oop_self10.md
    - 计算机系统I: https://howjul.com/2023/11/15/%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%B3%BB%E7%BB%9F%E6%9C%9F%E6%9C%AB%E8%80%83%E8%AF%95%E7%9B%B8%E5%85%B3/
  - 🌱 工具琐碎: 
    - Git学习笔记: ML/Git.md
    - Python学习笔记: ML/Python.md
    - Numpy学习笔记: ML/Numpy.md
    - Linux学习笔记: ML/Linux.md
    - Pytorch学习笔记:
      - Pytorch1: ML/Pytorch1.md
      - Pytorch2: ML/Pytorch2.md
      - Pytorch3: ML/Pytorch3.md
    - 网页美化: 琐碎/triviality.md
  - 🤖 人工智能基础:
    - 开始: ML/start.md
    - 动手学深度学习:
      - 第零章 安装: 
        - 安装: d2l/chapter0_installation/index.ipynb
      - 第一章 引言: 
        - 引言: d2l/chapter1_introduction/index.ipynb
      - 第二章 预备知识:
        - 数据操作: d2l/chapter2_preliminaries/2.1_数据操作(ndarray).ipynb
        - 数据预处理: d2l/chapter2_preliminaries/2.2_数据预处理(pandas).ipynb
        - 线性代数: d2l/chapter2_preliminaries/2.3_线性代数.ipynb
        - 微积分: d2l/chapter2_preliminaries/2.4_微积分.ipynb
        - 自动微分: d2l/chapter2_preliminaries/2.5_自动微分.ipynb
        - 概率: d2l/chapter2_preliminaries/2.6_概率.ipynb
        - 查阅文档: d2l/chapter2_preliminaries/2.7_查阅文档.ipynb
      - 第三章 线性神经网络:
        - 线性回归: d2l/chapter3_linear-networks/3.1_线性回归.ipynb
        - 线性回归的从零开始实现: d2l/chapter3_linear-networks/3.2_线性回归的从零开始实现.ipynb
        - 线性回归的简洁实现: d2l/chapter3_linear-networks/3.3_线性回归的简洁实现.ipynb
        - softmax回归: d2l/chapter3_linear-networks/3.4_softmax回归.ipynb
        - 图像分类数据集: d2l/chapter3_linear-networks/3.5_图像分类数据集.ipynb
        - softmax回归的从零开始实现: d2l/chapter3_linear-networks/3.6_softmax回归的从零开始实现.ipynb
        - softmax回归的简洁实现: d2l/chapter3_linear-networks/3.7_softmax回归的简洁实现.ipynb
      - 第四章 多层感知机:
        - 多层感知机: d2l/chapter4_multilayer-perceptrons/4.1_多层感知机.ipynb
        - 多层感知机的从零开始实现: d2l/chapter4_multilayer-perceptrons/4.2_多层感知机的从零开始实现.ipynb
        - 多层感知机的简洁实现: d2l/chapter4_multilayer-perceptrons/4.3_多层感知机的简洁实现.ipynb
        - 模型选择、欠拟合和过拟合: d2l/chapter4_multilayer-perceptrons/4.4_模型选择、欠拟合和过拟合.ipynb
        - 权重衰减: d2l/chapter4_multilayer-perceptrons/4.5_权重衰减.ipynb
        - 暂退法(dropout): d2l/chapter4_multilayer-perceptrons/4.6_暂退法(Dropout).ipynb
        - 前向传播、反向传播和计算图: d2l/chapter4_multilayer-perceptrons/4.7_前向传播、反向传播和计算图.ipynb
        - 数值稳定性和模型初始化: d2l/chapter4_multilayer-perceptrons/4.8_数值稳定性和模型初始化.ipynb
        - 环境和分布偏移: d2l/chapter4_multilayer-perceptrons/4.9_环境和分布偏移.ipynb
        - 实战:预测房价: d2l/chapter4_multilayer-perceptrons/4.10_实战Kaggle比赛：预测房价.ipynb
      - 第五章 深度学习计算:
        - 层和块: d2l/chapter5_deep-learning-computation/5.1_层和块.ipynb
        - 参数管理: d2l/chapter5_deep-learning-computation/5.2_参数管理.ipynb
        - 延后初始化: d2l/chapter5_deep-learning-computation/5.3_延后初始化.ipynb
        - 自定义层: d2l/chapter5_deep-learning-computation/5.4_自定义层.ipynb
        - 读写文件: d2l/chapter5_deep-learning-computation/5.5_读写文件.ipynb
        - GPU: d2l/chapter5_deep-learning-computation/5.6_GPU.ipynb
      - 第六章 卷积神经网络:
        - 从全连接层到卷积: d2l/chapter6_convolutional-neural-networks/6.1_从全连接层到卷积.ipynb
        - 图像卷积: d2l/chapter6_convolutional-neural-networks/6.2_图像卷积.ipynb
        - 填充和步长: d2l/chapter6_convolutional-neural-networks/6.3_填充padding和步长strides.ipynb
        - 多输入多输出通道: d2l/chapter6_convolutional-neural-networks/6.4_多输入多输出通道.ipynb
        - 汇聚层: d2l/chapter6_convolutional-neural-networks/6.5_汇聚层.ipynb
        - 卷积神经网络(LeNet): d2l/chapter6_convolutional-neural-networks/6.6_卷积神经网络(LeNet).ipynb
      - 第七章 现代卷积神经网络:
        - 引言: d2l/chapter7_convolutional-modern/7.0_引言.ipynb
        - 深度卷积神经网络(AlexNet): d2l/chapter7_convolutional-modern/7.1_深度卷积神经网络(AlexNet).ipynb
        - 使用块的网络(VGG): d2l/chapter7_convolutional-modern/7.2_使用块的网络(VGG).ipynb
        - 含并行连接的网络(GoogLeNet): d2l/chapter7_convolutional-modern/7.4_含并行连接的网络(GoogLeNet).ipynb
        - 批量规范化: d2l/chapter7_convolutional-modern/7.5_批量规范化.ipynb
        - 残差网络(ResNet): d2l/chapter7_convolutional-modern/7.6_残差网络(ResNet).ipynb
        - 稠密连接网络(DenseNet): d2l/chapter7_convolutional-modern/7.7_稠密连接网络(DenseNet).ipynb
    - 李宏毅机器学习课程:
      - Lec1 Introduction of Deep Learning: ML/Lec1_Introduction of Deep Learning.md
      - Lec2 What to do if my network fails to train:
        - 0_General Guidance: ML/Lec2_0_General Guidance.md
        - 1_Local Minimum And Saddle Point: ML/Lec2_1_Local Minimum And Saddle Point.md
        - 2_Batch and Momentum: ML/Lec2_2_Batch and Momentum.md
        - 3_Adaptive Learning Rate: ML/Lec2_3_Adaptive Learning Rate.md
        - 4_Batch Normalization: ML/Lec2_4_Batch Normalization.md
        - 5_Classification: ML/Lec2_5_Classification.md
      - Lec3 Image as input: ML/Lec3_CNN.md
      - Lec4 Sequence as input: 
        - 1_Self-attention: ML/Lec4_1_Self-attention.md
        - 2_Self-attention: ML/Lec4_2_Self-attention.md
      - Lec5 Sequence to sequence:
        - 1_Transformer: ML/Lec5_1_Transformer.md
        - 2_Transformer: ML/Lec5_2_Transformer.md
      - Lec6 Generation:
        - 1_GAN: ML/Lec6_1_GAN.md
        - 2_GAN: ML/Lec6_2_GAN.md
        - 3_GAN: ML/Lec6_3_GAN.md
        - 4_GAN: ML/Lec6_4_GAN.md
      - Lec7 Self-supervised learning for Speech and Image:
        - 1_BERT: ML/Lec7_1_BERT_P1.md
        - 2_BERT: ML/Lec7_2_BERT_P2.md
        - 3_BERT: ML/Lec7_3_BERT_P3.md
      - Lec8 Auto-encoder/ Anomaly Detection:
        - 1_Auto-encoder: ML/Lec8_1_Auto-encoder_P1.md
        - 2_Auto-encoder: ML/Lec8_2_Auto-encoder_P2.md
      - Lec9 Explainable AI:
        - 1_Explainable AI: ML/Lec9_1_Explainable AI_P1.md
        - 2_Explainable AI: ML/Lec9_2_Explainable AI_P2.md
  - ⭐️ 人工智能安全: https://www.yuque.com/howjul/ypockp
  
# [UI]
## [top]
theme:
  name: material
  custom_dir: overrides
  # palette:
  #   - scheme: default # 日间模式
  #     primary: teal # 上方的
  #     accent: teal # 链接等可交互元件的高亮色
  #     toggle:
  #       icon: material/weather-night # 图标
  #       name: 切换至夜间模式 # 鼠标悬浮提示
  #   - scheme: sunset-glow-dark # 夜间模式
  #     primary: teal
  #     accent: teal
  #     toggle:
  #       icon: material/weather-sunny
  #       name: 切换至日间模式
  palette: 
    - scheme: forest
      toggle:
        icon: material/weather-night # 图标(可改，下同)
        name: Switch to dark mode
    - scheme: forest dark
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  # 导航栏
  features:
    - navigation.tabs # 使用Tab来进行分类
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    # - navigation.expand # 打开Tab时左侧目录全部展开
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - content.code.copy # 可以通过按钮复制代码
    - content.code.annotate
  language: zh # 一些提示性的文字会变成中文
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  logo: ./img/logo.jpg
  favicon: ./img/logo.ico
## edit_uri: edit/main/docs # 编辑按钮跳转的链接
## [top-right corner]
repo_url: https://github.com/howjul/note # 右上角点击跳转的链接
repo_name: note # 右上角的名字
## [bottom-left corner]
copyright: '本页面的全部内容在 <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh">CC BY-SA 4.0</a> 和 <a href="https://github.com/zTrix/sata-license">SATA</a> 协议之条款下提供'
## [bottom-right corner]
extra:
  vssue: shafish  # 随便填值，主要是设置{% set vssue = config.extra.vssue %}时，vssue初始值可用
  social: # icons
    - icon: fontawesome/brands/weixin
      link: https://wx.qq.com/
      name: 微信号 | HowJul.(邮箱联系)
    - icon: fontawesome/solid/paper-plane
      link: mailto:zjuzhz@outlook.com
      name: Outlook 
    - icon: fontawesome/brands/qq
      link: https://user.qzone.qq.com
      name: QQ | 凰亦(邮箱联系) # 鼠标悬浮提示
    - icon: fontawesome/brands/github
      link: https://github.com/howjul
      name: GitHub | howjul
  analytics:
    provider: false
    property: G-XXXXXXXXXX
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/heart
          name: This page was helpful
          data: 1
          note: >-
            谢谢支持, v我五十🤗
        - icon: material/heart-broken
          name: This page could be improved
          data: 0
          note: >- 
            会改的😭

# [Extensions]
plugins:
  - search: # 现在还不支持中文搜索 支持之后可以设置语言
    # insider已经支持中文的分词搜索了 https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/
      lang:
        - en
        - ja
  - tags # 给单篇文章添加标签 https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags
  - statistics
  - mkdocs-jupyter:
      include_source: True
      execute: False
      ignore: ["*.py"]
  #- encryptcontent: {}
      #global_password: '1221504'

markdown_extensions:
  #列表
  - def_list
  - pymdownx.tasklist:
        custom_checkbox: true
  # latex支持
  - pymdownx.arithmatex: 
      generic: true
  # 给图片后面添加{width="300"}设置大小
  # 按钮
  - attr_list 
  - md_in_html
  #锚点
  - toc:
      permalink: true # 固定标题位置为当前位置
  # 代码块
  - pymdownx.highlight: # 代码块高亮
      linenums: false # 显示行号
      auto_title: true # 显示编程语言名称
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等
  - admonition # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#inline-blocks
  - pymdownx.details # admonition需要
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables #表格
  - footnotes #注脚
  #图标
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.emoji.twemoji 
  #     emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde


extra_javascript:
  - https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
  # - javascripts/snow.js # 背景雪花
  - javascripts/baidu.js

extra_css:
  - css/no-footer.css # 不使用底部的翻页
  - css/unordered-list-symbols.css # multiplt unordered list symbols
  - css/flink.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  - css/stytlesheets.css 
  - css/admonition.css
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css # 字体
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-lite-webfont@1.1.0/style.css
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-tc-webfont@1.0.0/style.css
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css

