# [Info]
site_name: HowJul的学习笔记 # 左上角标题
site_url: https://howjul.github.io/note
site_author: zhz
site_description: zhz's site

# [Navigtion]
nav:
  - Home: 
    - Home: index.md
    - Secondary disease: head.md
    - About: about.md
  - Conclusion:
    - 说明: ./课程总结/index.md
    - 大三春夏: ./课程总结/大三春夏.md
    - 大三秋冬: ./课程总结/大三秋冬.md
    - 大二暑假: ./课程总结/大二暑假.md
    - 大二春夏: ./课程总结/大二春夏.md
    - 大二秋冬: ./课程总结/大二秋冬.md
    - 大一暑假: ./课程总结/大一暑假.md
    - 大一春夏: ./课程总结/大一春夏.md
    - 大一秋冬: ./课程总结/大一秋冬.md
  - Course: 
    - 说明: ./course.md
    # - 计算机系统一: 系统一/系统一.md
    - 技术沟通:
      - 1.文献检索: 技术沟通/1 文献检索.md
      - 2.文献阅读: 技术沟通/2 文献阅读.md
      - 3.文献综述: 技术沟通/3 文献综述.md
      - 4.技术文档的结构: 技术沟通/4 技术文档的结构.md
      - 5.技术文档的语言: 技术沟通/5 技术文档的语言.md
      - 6.演示方法: 技术沟通/6 演示方法.md
      - 7.演讲方法: 技术沟通/7 演讲方法.md
    - 计算机系统二: 
      - 1.OS Services & Structures: 系统二/1. OS Services & Structures (11.7、11.14).md
      - 2.OS Structures: 系统二/2. OS Structures (11.17).md
      - 3.Process: 系统二/3. Process(11.17、11.21、11.24).md
      - 4.Threads: 系统二/4. Threads(11.24、11.28、12.1).md
      - 5.Threads_b: 系统二/5. Threads_b(12.1).md
      - 6.CPU_Scheduling: 系统二/6. CPU_Scheduling(12.5、12.8、12.12).md
      - 7.Mars: 系统二/7. Mars(12.12).md
      - 8.Synchronization Tools: 系统二/8. Synchronization Tools (12.14).md
    - 数据结构基础:
      - exam: 
        - 说明: FDS/试卷/试卷.md
        - 21-22期中卷: FDS/试卷/21-22 期中卷.md
        - 期中卷: FDS/试卷/期中卷.md
      # - hw:
      #   - hw1-7: FDS/fds_hw/fds_hw1-7.md
      #   - hw8: FDS/fds_hw/fds_hw8.md
      #   - hw9: FDS/fds_hw/fds_hw9.md
      #   - hw10: FDS/fds_hw/fds_hw10.md
      #   - hw11: FDS/fds_hw/fds_hw11.md
      #   - hw12: FDS/fds_hw/fds_hw12.md
      #   - hw13: FDS/fds_hw/fds_hw13.md
      #   - hw14: FDS/fds_hw/fds_hw14.md
      #   - hw15: FDS/fds_hw/fds_hw15.md
      - lec:
        - lec1-6: FDS/fds_lec/fds_lec1-6.md
        - lec7: FDS/fds_lec/fds_lec7.md 
        - lec8: FDS/fds_lec/fds_lec8.md 
        - lec9: FDS/fds_lec/fds_lec9.md 
        - lec10: FDS/fds_lec/fds_lec10.md 
        - lec11: FDS/fds_lec/fds_lec11.md 
        - lec12: FDS/fds_lec/fds_lec12.md 
        - lec13-14: FDS/fds_lec/fds_lec13&&lec_14.md 
    - 面向对象程序设计:
      - lec:
        - exam: OOP/oop_lec/oop_exam.md 
        - lec11: OOP/oop_lec/oop_lec11.md 
        - lec12: OOP/oop_lec/oop_lec12.md 
        - lec13: OOP/oop_lec/oop_lec13.md 
        - lec14: OOP/oop_lec/oop_lec14.md 
        - lec15: OOP/oop_lec/oop_lec15.md 
      - selfstudy:
        - self1: OOP/oop_self/oop_self1.md 
        - self2: OOP/oop_self/oop_self2.md 
        - self3: OOP/oop_self/oop_self3.md 
        - self4: OOP/oop_self/oop_self4.md 
        - self5: OOP/oop_self/oop_self5.md 
        - self6: OOP/oop_self/oop_self6.md 
        - self7: OOP/oop_self/oop_self7.md 
        - self8: OOP/oop_self/oop_self8.md 
        - self9: OOP/oop_self/oop_self9.md 
        - self10: OOP/oop_self/oop_self10.md 
    - 高级数据结构与算法分析:
      - 1.AVL Tree&Splay Tree: ADS/1. AVL Tree&Splay Tree 2.28.md
      - 2.Red-Black Trees&B+ Trees: ADS/2. Red-Black Trees&B+ Trees3.7.md
      - 3.Inverted File Index: ADS/3. Inverted File Index.md
      - 4.Leftist Heaps and Skew Heaps: ADS/4. Leftist Heaps and Skew Heaps.md
      - 5.Binomial Queue: ADS/5. Binomial Queue.md
      - 6.Backtracking: ADS/6. Backtracking.md
      - 7.Divide and Conquer: ADS/7. Divide and Conquer.md
      - 8.Dynamic Programming: ADS/8. Dynamic Programming.md
      - 9.Greedy Algorithms: ADS/9. Greedy Algorithms.md
      - 10.NP-Completeness: ADS/10. NP-Completeness.md
      - 11.Approximation: ADS/11. Approximation.md
      - 12.Local Search: ADS/12. Local Search.md
      - 13.Randomized Algorithms: ADS/13. Randomized Algorithms.md
      - 14.Parallel Algorithms: ADS/14. Parallel Algorithms.md
      - 15.External Sorting: ADS/15. External Sorting.md
      - 参考: ADS/inference.md
    - 计算机系统三:
      - 第3课: 系统三/第三课 3.6.md
      - 第4课: 系统三/第四课 3.9.md
      - 第5课: 系统三/第五课 3.13.md
      - 第6课: 系统三/第六课 3.16.md
      - 第7课: 系统三/第七课 3.20.md
      - 第8课: 系统三/第八课 3.23.md
      - 第9课: 系统三/第九课 3.27.md
      - 第10课: 系统三/第十课 3.30.md
      - 第15课: 系统三/第十五课 4.17.md
      - 第16课: 系统三/第16课 4.20.md
      - 第17课: 系统三/第17课 4.24.md
      - 第18课: 系统三/第18课 4.27.md
      - 第19课: 系统三/第19课 5.4.md
      - 第20课: 系统三/第20课 5.8.md
      - 第21课: 系统三/第21课 5.11.md
      - 第22课: 系统三/第22课 5.15.md
      - 第23课: 系统三/第23课 5.18.md
      - 第24课: 系统三/第24课 5.22.md
      - 第25课: 系统三/第25课 5.25.md
      - 第26课: 系统三/第26课 5.29.md
      - 第27课: 系统三/第27课 6.1.md
      - 第28课: 系统三/第28课 6.5.md
      - 第29课: 系统三/第29课 6.8.md
      - 操作系统导论笔记: 系统三/操作系统导论笔记.md
    - 密码学: 密码学/explain.md
    - 软件安全: 
      - 0.Introduce: 软件安全/0. Introduce.md
      - 1.Overview: 软件安全/1. Overview.md
      - 2.Basic Principles: 软件安全/2. Basic Principles.md
      - 3.Buffer Overflow: 软件安全/3. Buffer Overflow.md
      - 4.Ret2libc & ROP: 软件安全/4. Ret2libc & ROP.md
      - 5.ROP & BROP: 软件安全/5. ROP & BROP.md
      - 6.Format String Attack: 软件安全/6. 格式化字符串漏洞.md
      - 7.Static Analysis: 软件安全/7. 静态分析.md
      - 8.Symbolic&Concolic Execution: 软件安全/8. Symbolic&Concolic Execution.md
      - 9.Taint Analysis: 软件安全/9. Taint Analysis.md
      - 10.fuzz: 软件安全/10. fuzz.md
      - 11.SFI&CFI: 软件安全/11. SFI & CFI.md
    - 数据安全与隐私保护: 
      - 1.Course Overview: 数据安全/1. Course Overview.md
      - 2.User Authentication: 数据安全/2. User Authentication.md
      - 3.Unix Discretionary Access Control: 数据安全/3.  Unix Discretionary Access Control.md
      - 4.MAC and Intergrity Protection: 数据安全/4. MAC and Intergrity Protection.md
      - 5.Role Based Access Control: 数据安全/5. Role Based Access Control.md
      - 6.Modern Crypto: 数据安全/6. Modern Crypto.md
      - 7.Stream Ciphers and CPA Security: 数据安全/7. Stream Ciphers and CPA Security.md
      - 8.PRF, CPA Security and CCA Security: 数据安全/8. PRF, CPA Security and CCA Security.md
      - 9. Message Authentication Code: 数据安全/9. Message Authentication Code.md
      - 10. Number Theory Basics: 数据安全/10. Number Theory Basics.md
      - 11. Key Management and The Need for Public Key Cryptography: 数据安全/11. Key Management and The Need for Public Key Cryptography.md
      - 13. RSA Encryption: 数据安全/13. RSA Encryption.md
      - 14. Digital Signature: 数据安全/14. Digital Signature.md
      - 15. Differential Privacy: 数据安全/15. Differential Privacy.md
    - 机器人导论: 
      - 第三课 微控制器: 机器人导论/第三课 3.6 微控制器.md
      - 第四课 机器人传感器: 机器人导论/第四课 3.10 机器人传感器.md
      - 第五课 机器人驱动原理概述: 机器人导论/第五课 3.13 机器人驱动原理概述.md
      - 第六课 机器人驱动原理概述-2: 机器人导论/第六课 3.17 机器人驱动原理概述-2.md
      - 第七课 机器人设计与传动-1: 机器人导论/第七课 3.20 机器人设计与传动-1.md
      - 第八课 机器人设计与传动-2: 机器人导论/第八课 3.24 机器人设计与传动-2.md
      - 第九课 机器人运动学和坐标变换: 机器人导论/第九课 3.27 机器人运动学和坐标变换.md
      - 第十课 里程估计: 机器人导论/第十课 3.31 里程估计.md
      - 第十一课 机器人视觉: 机器人导论/第十一课 4.3 机器人视觉.md
      - 第十二课 规划导论: 机器人导论/第十二课 4.7 规划导论.md
      - 第十三课 集群: 机器人导论/第十三课 4.10 集群.md
    - 中国现当代小说赏析: 
      - 中国现当代小说简脉: 中国现当代小说赏析/中国现当代小说赏析.md
      - 沈从文小说赏析: 中国现当代小说赏析/沈从文小说赏析.md
      - 张爱玲小说赏析: 中国现当代小说赏析/张爱玲小说赏析.md
      - 谌容小说赏析: 中国现当代小说赏析/谌容小说赏析.md
      - 余华小说赏析: 中国现当代小说赏析/余华小说赏析.md
      - 刘震云小说赏析: 中国现当代小说赏析/刘震云小说赏析.md
      - 鬼子小说赏析: 中国现当代小说赏析/鬼子小说赏析.md
  - ML: 
    - Git学习笔记: ML/Git.md
    - Python学习笔记: ML/Python.md
    - Numpy学习笔记: ML/Numpy.md
    - Linux学习笔记: ML/Linux.md
    - Pytorch学习笔记:
      - Pytorch1: ML/Pytorch1.md
      - Pytorch2: ML/Pytorch2.md
      - Pytorch3: ML/Pytorch3.md
    - 李宏毅机器学习课程:
      - Lec1 Introduction of Deep Learning: ML/Lec1 Introduction of Deep Learning.md

  - Friend: Friend/link.md
  - Strange: 
    - 209志怪录: Friend/pet.md
    - 丽泽秘闻: Friend/lize.md
    - 1/365 night: Friend/night.md
  - Triviality:
    - 网页美化: 琐碎/triviality.md
  
# [UI]
## [top]
theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: default # 日间模式
      primary: teal # 上方的
      accent: teal # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  # 导航栏
  features:
    - navigation.tabs # 使用Tab来进行分类
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    # - navigation.expand # 打开Tab时左侧目录全部展开
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - content.code.copy # 可以通过按钮复制代码
    - content.code.annotate
  language: zh # 一些提示性的文字会变成中文
  icon:
    repo: fontawesome/brands/github
  logo: ./img/logo.jpg
  favicon: ./img/logo.ico
## edit_uri: edit/main/docs # 编辑按钮跳转的链接
## [top-right corner]
repo_url: https://github.com/howjul/note # 右上角点击跳转的链接
repo_name: note # 右上角的名字
## [bottom-left corner]
copyright: HowJul. CC-BY-NC-4.0 # 左下角的版权声明
## [bottom-right corner]
extra:
  vssue: shafish  # 随便填值，主要是设置{% set vssue = config.extra.vssue %}时，vssue初始值可用
  social: # icons
    - icon: fontawesome/brands/weixin
      link: https://wx.qq.com/
      name: 微信号 | HowJul.(邮箱联系)
    - icon: fontawesome/solid/paper-plane
      link: mailto:zjuzhz@outlook.com
      name: Outlook 
    - icon: fontawesome/brands/qq
      link: https://user.qzone.qq.com
      name: QQ | 凰亦(邮箱联系) # 鼠标悬浮提示
    - icon: fontawesome/brands/github
      link: https://github.com/howjul
      name: GitHub | howjul
  analytics: 
    provider: google
    property: G-XXXXXXXXXX
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/heart
          name: This page was helpful
          data: 1
          note: >-
            谢谢支持, v我五十🤗
        - icon: material/heart-broken
          name: This page could be improved
          data: 0
          note: >- 
            会改的😭

# [Extensions]
plugins:
  - search: # 现在还不支持中文搜索 支持之后可以设置语言
    # insider已经支持中文的分词搜索了 https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/
      lang:
        - en
        - ja
  - tags # 给单篇文章添加标签 https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags
  #- encryptcontent: {}
      #global_password: '1221504'

markdown_extensions:
  #列表
  - def_list
  - pymdownx.tasklist:
        custom_checkbox: true
  # latex支持
  - pymdownx.arithmatex: 
      generic: true
  # 给图片后面添加{width="300"}设置大小
  # 按钮
  - attr_list 
  - md_in_html
  #锚点
  - toc:
      permalink: true # 固定标题位置为当前位置
  # 代码块
  - pymdownx.highlight: # 代码块高亮
      linenums: false # 显示行号
      auto_title: true # 显示编程语言名称
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等
  - admonition # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#inline-blocks
  - pymdownx.details # admonition需要
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables #表格
  - footnotes #注脚
  #图标
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde


extra_javascript:
  # latex支持
  # check https://squidfunk.github.io/mkdocs-material/reference/mathjax/?h=math for more information
  # notice `curl https://polyfill.io/v3/polyfill.min.js?features=es6 > docs/mkdocs/javascripts/polyfill.min.js && curl https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js > docs/mkdocs/javascripts/tex-mml-chtml.js` not works... because there are other resources that need to load
  
  # - javascripts/mathjax.js
  # - https://polyfill.io/v3/polyfill.min.js?features=es6
  # - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js
  
  - javascripts/busuanzi.pure.mini.js
  
  # - https://polyfill.io/v3/polyfill.min.js?features=es6
  # - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # https://cdn.bytedance.com/?query=mathjax&version=3.2.0
  
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - css/no-footer.css # 不使用底部的翻页
  - css/unordered-list-symbols.css # multiplt unordered list symbols
  - css/flink.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

